# Generated by Django 4.2.3 on 2023-08-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_emails', '0002_employee_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
